@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
actor teacher
participant System

activate teacher
activate System
teacher -> System: login
System -> teacher: login success
deactivate System
teacher -> System: choose option schedule an extraordinary class
activate System
System -> teacher: Request class information
deactivate System
teacher -> System: enter class information
activate System
System -> teacher: class created

deactivate System
deactivate teacher

@enduml