@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
actor user
participant System

activate user
activate System

user -> System: asks to create a post-it

System --> user: asks which board would like to create the post-it

deactivate System

user -> System: chooses a board

activate System

System --> user: shows available cells and asks to choose one

deactivate System

user -> System: chooses a cell

activate System

System --> user: asks for post-it data

deactivate System

user -> System: types data for post-it

activate System

System --> user: shows operation success

deactivate System
deactivate user

@enduml