@startuml
actor user
participant System

activate user
activate System
user -> System: login
System -> user: login success
deactivate System
user -> System: choose option meeting
activate System
user -> System: choose list Meeting
user -> System: choose type of meeting
user -> System: choose meeting
System -> user: list the meetings

deactivate System
deactivate user
@enduml